language: node_js
node_js:
  - "14"

os:
  - linux
dist: xenial # to use Ubuntu 16.04

git:
  depth: 3

env:
  global:
    - secure: afkoh+un0tMiyqqznPBqoM6WRgLcu7qmA3oDfRq2Eqx+UPRJDOJyQ5GElx/SoNXUHYDrNauDmx1dkqVuHZzMCqc3WhMeQDKawPJbw1CgB6KddIrRhaA2bDZ+pNLcS+lU39aszrLfVOxxRz0V80Vjev4RDQ/PvscYrkjiOEO3S5KkkIEUx0YKvi4n7ve9NnyEur9j4h5h7DEDTR+xhuyH8x8JcK4W3BW2SyIpCNeJO0A2ZBIG/kstU0QWTS5S5D8DZByMFTI+R+usq+Djgi1HpeqTmsJ6OKjpA1qO5MbOcyM+MRLWVLZcfgLV7fz1raQpj1VaIVJzebP9/f4gaBKcmmYSm68WBT0DoVmPG+P5YhGxETJlYSbfFzkvcxiWC4MMAgh+I56x7J2d2E8552eXTa5s85kdnmZzmusLdj3DOfoozNs+lMGUnQlcaJfEZCoCpQgchIe817B+SlVIRvC+G2RYQPABc/M30PyqFANgFpdU5KY1qbx7vka7X52zwpFeYrzunJmNXNFWT6Fo014SgR7E/tYC54IROITZgCx/nA1WiR4Ka9vnUmkJ9A0lOAAeshCPhgUEpbatZu+l9W8yBGZ6Zf7ZwOyZgSbx8AugPYtZeoSe6EvrTU3ghGb0MeMzWw8V1OUS+dTDRJ90TPS3w5As+n2bNuxs+KFNm2+zGDw== # CODECLIMATE
    - secure: VQffWPp3fa0UrshHHtspgvRj9WIaoOgkg0+5O5AFFPbwvEh/ACHeLZbxFzlMyuoahH9MZ4bYMVEnZvQjg9v86Z24+cH1bYZrCBbPqkKiM0Z3eUhTeZZlDBYbBmY1WtDZarMGHjznkz0kFXgHbggE1cqmDs/WDnvdZBhLTKOKKlZRM4iTPsmP/DWd0neQPDb7qStYx1Fp+lXvb+os3h09czDNY2jx+9LF3k3jxOWfPOEYdlKwp5dOUG8MTzMN2hhdy7XU9uLqMtiB/sS0DqafvgmlHvgnJmkx4Hdn1Ae3O0amVxJbx6e+J821AfrSCQqkLG9IX6mvplXZ8BRHn+9cgRXKJbyhFb2mIkJHwylatoPHagW9Nql62LcYTTsdnrgcYFpfciAEnIfNHwXm8IM3e80UPsvaZR2SpCmP7CdZJ8GFDdAzBtjgPyS311AKGMfergQbET8EZ34AVxfNjj0UTP7uJ9Mm35kd2zEK8bV1ZPbxP/EIKOn6IL6nqXoHhJphgKHbV/OdTUaHd7p5RUjSHGZdMM8DYqkSW7cMprc98//lUnA1O1HjnLbBBHOzK4XEKeEprM/9GCvOYLOTwABa6IgiltYf6JEEy/MHnBtYaBVk/bnj/LOV2OCANk9qBlmTLL+VRRmpnmQYV7WQIXhwP8GRZt04fXHgyJfCbWxXbKI= # COVERALLS

addons:
  firefox: latest
  chrome: stable

matrix:
  fast_finish: true

before_install:
  - source travisci/before_install.sh
install:
  - bash travisci/install.sh
after_install:
  - npm rebuild node-sass
before_script:
  - source travisci/before_script.sh # starts in the same shell
script:
  - bash travisci/script.sh
after_success:
  - source travisci/after_success.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  apt: true
  bundler: true
  directories:
    - ./node_modules
    - ./examples/angular-cli-12/node_modules
    - ./examples/angular-cli-material/node_modules
    - ./examples/universal/node_modules
    - ./.github
