version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-stretch-browsers # to use the latest version switch to node:latest-browsers
      # Environment variable for all commands executed in the primary container
        environment:
          NODE_ENV: test
          CI: yes
    steps:
      - checkout
      - run:
          name: npm-install-npm-latest
          command: sudo npm install -g npm@5.8.0
      - run:
          name: npm-install-global
          command: sudo npm install -g codeclimate-test-reporter
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: node-sass-clean
          command: npm rebuild node-sass --force
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
            - "examples/angular-cli/node_modules"
            - "examples/angular-cli-material/node_modules"
            - "examples/universal/node_modules"
            - "examples/systemjs/node_modules"
      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release
            sudo apt-get install libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      # prepare
      - run:
          name: run-clean-all
          command: npm run clean:all
      - run:
          name: run-install-demo-systemjs
          command: cd examples/systemjs && npm install
      - run:
          name: run-install-demo-angular-cli
          command: cd examples/angular-cli && npm install
      - run:
          name: run-install-demo-angular-cli-material
          command: cd examples/angular-cli-material && npm install
      - run:
          name: run-install-demo-universal
          command: cd examples/universal && npm install
      # build the library and copy it in all examples
      - run:
          name: run-build-all-libray
          command: npm run build:all
      # main angular-cli
      - run:
          name: run-build-dev-main-angular-cli
          command: npm run build:main:dev
      - run:
          name: run-build-prod-main-angular-cli
          command: npm run build:main:prod
      # angular-cli
      - run:
          name: run-build-dev-demo-angular-cli
          command: cd examples/angular-cli && npm run build:dev
      - run:
          name: run-build-prod-aot-demo-angular-cli
          command: cd examples/angular-cli && npm run build:prod
      # angular-cli-material
      - run:
          name: run-build-dev-demo-angular-cli-material
          command: cd examples/angular-cli-material && npm run build:dev
      - run:
          name: run-build-prod-aot-demo-angular-cli-material
          command: cd examples/angular-cli-material && npm run build:prod
      # universal
      - run:
          name: run-build-dev-demo-universal
          command: cd examples/universal && npm run build:dev
      - run:
          name: run-build-prod-aot-demo-universal
          command: cd examples/universal && npm run build:prod
      - run:
          name: run-build-ssr-demo-universal
          command: cd examples/universal && npm run build:ssr
      - run:
          name: run-build-prerender-demo-universal
          command: cd examples/universal && npm run build:prerender
      # test the library
      - run:
          name: run-test-library
          command: npm run test:ci
      - run:
          name: run-e2e-library
          command: npm run e2e:ci
      # docs
      - run:
          name: run-docs
          command: npm run docs:typedoc
# FIXME locally it's working, but not on circleci, why???
#      - run:
#          name: run-compodoc
#          command: npm run docs:compodoc
      - run:
          name: run-codeclimate
          command: npm run codeclimate
      - run:
          name: run-coveralls
          command: npm run coveralls
